name: Metrics
on:
  # Schedule updates (every 11 hour)
  schedule: [{cron: "0 */11 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: im-alfa
          debug: no
          template: classic
          base: header, activity, repositories
          base_indepth: yes
          commits_authoring: alex.altea@ivao.aero
          config_timezone: Europe/Dublin
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_ignored: html, css, javascript
          plugin_languages_skipped: im-alfa/metrics, im-alfa/passport-ivao
          plugin_achievements_threshold: C
          plugin_introduction_title: yes
          plugin_projects: yes
          plugin_projects_limit: 4
