on:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Generate README.md
      uses: teoxoy/profile-readme-stats@v2
      with:
        token: ${{ secrets.METRICS_TOKEN }}
        includeForks: false
    - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name ${{ secrets.USER_NAME }}
        git config user.email ${{ secrets.USER_EMAIL }}
        git add .
        git commit -m "update profile stats"
        git push
        fi
